# Generated by Django 2.2.1 on 2019-05-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20190528_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
