# Generated by Django 2.2.1 on 2019-05-28 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_auto_20190528_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cookbook.Colour'),
        ),
    ]
