# Generated by Django 2.2.1 on 2019-05-29 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_auto_20190528_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientlist',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='ingredientlist',
            name='unit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='cookbook.Unit'),
        ),
    ]
