# Generated by Django 2.2.1 on 2019-05-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0006_auto_20190529_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientlist',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
